### PR TITLE
Dropbox. File unpload using /chunked_upload API method

### LINKED ISSUE #26: Dropbox back-end bug
Example file content: line1 line2
If use dropbox=2.2.0 package (or 2.1, or 2.0), I will get file with incorrect content: b"line1\nline2"
But if I use dropbox==1.6 package to upload file, I will get file with correct content.

### PR DESCRIPTION
**Pull request by dimka665**
Rational.

I could not backup media to Dropbox without this patch. Backup file size was ~1Gb. While uploading parted file 'serve-date.tar.gz.0' (145 mb) there are was dropbox any error and backup process fails.

Now we uses:

1. /chunked_upload/ API method to upload numbered files (part of backup file)
2. few retries on upload fail

We gets:
+ we can increase file size limit up to 10 Gb
+ we can choose chunk size to minimize transfer losses
+ we retry chunk upload i.e. on connection lags

This patch fixes
#26 and #24

### CODE REVIEW

**Comment by dimka665** [comment]
PS
I know about Dropbox library ChunkedUploader class. It has one bad feature which prevent it usage.
Using StringIO class.

**Comment by benjaoming** [comment]
@mjs7231 what do you think?

Looks good to me, but am unable to test this.

**Comment by eriktelepovsky** [comment]
+1

**Comment by eriktelepovsky** [comment]
When I run dbbackup command, I got

```
TypeError: must be type, not classobj
```

Exception Location:	**dbbackup/storage/dropbox_storage.py in __init__, line 41**

**Comment by dimka665** [comment]
What is your python version? Show full traceback please.

**Comment by eriktelepovsky** [comment]
Python 2.7.3
Django 1.5

```
Traceback:
File "/home/archivis/environment/local/lib/python2.7/site-packages/dbbackup/management/commands/dbbackup.py" in handle
  45.             self.storage = BaseStorage.storage_factory()
File "/home/archivis/environment/local/lib/python2.7/site-packages/dbbackup/storage/base.py" in storage_factory
  33.         return storage_module.Storage()
File "/home/archivis/environment/local/lib/python2.7/site-packages/dbbackup/storage/dropbox_storage.py" in __init__
  41.         super(Storage, self).__init__()

Exception Type: TypeError at 
Exception Value: must be type, not classobj
```

**Comment by dimka665** [comment]
Please try again.

**Comment by eriktelepovsky** [comment]
Thanks, moving forward, but I get another exception:

```
Traceback:
File "/home/archivis/environment/local/lib/python2.7/site-packages/dbbackup/management/commands/dbbackup.py" in handle
  53.                 self.save_new_backup(database, database_key)
File "/home/archivis/environment/local/lib/python2.7/site-packages/dbbackup/management/commands/dbbackup.py" in save_new_backup
  73.         self.storage.write_file(outputfile, filename)
File "/home/archivis/environment/local/lib/python2.7/site-packages/dbbackup/storage/dropbox_storage.py" in write_file
  122.             self.dropbox.commit_chunked_upload(numbered_file_full_path, upload_id)

Exception Type: AttributeError at 
Exception Value: 'DropboxClient' object has no attribute 'commit_chunked_upload'
```

**Comment by dimka665** [comment]
What version of "dropbox" python module are you using? Try last one,
dropbox==2.2.0

2015-05-27 14:10 GMT+03:00 Erik Telepovský <notifications@github.com>:

**Comment by eriktelepovsky** [comment]
Yeah, I figured it out right after I posted previous comment, so I changed it. 

It would be also great if **FILE_SIZE_LIMIT** is configurable or set to maximum allowed size (10 GB).

**Comment by benjaoming** [comment]
@mjs7231 I'm merging this now, since it seems to be the only way to have it tested... so just don't release anything before we're sure it's all good and stable :)

**Pull request merged**
